import 'bootstrap/dist/css/bootstrap.css'
import '@/assets/styles/main.css'
import '@fontsource/inter/400.css'
import '@fontsource/inter/700.css'
import '@fontsource/inter/800.css'
import 'vuetify/styles'
